server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /ml-api {
        return 301 /ml-api/;
    }

    location /ml-api/ {
        proxy_pass http://fastapi-backend:8000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /crud-api {
        return 301 /crud-api/;
    }

    location /crud-api/ {
        proxy_pass http://spring-backend:8080/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
